### ISSUE TITLE
Error while adding iOS platform

### ISSUE THREAD

**Issue by ghost** [CreativeSDK/phonegap-template-csdk-image-editor#4]
> Installing "phonegap-plugin-csdk-client-auth" for ios
> 
> 
> Error during processing of action! Attempting to revert...
> 
> 
> Failed to install 'phonegap-plugin-csdk-client-auth':CordovaError: Uh oh!
> cannot find "/Volumes/DATA/work/Photo Editor/tempcsdk/plugins/phonegap-plugin-csdk-client-auth/src/ios/AdobeCreativeSDKFrameworks/AdobeCreativeSDKCore.framework/Versions/A/Resources/AdobeCreativeSDKCoreResources.bundle" ios <resource-file>
>     at install (/Volumes/DATA/work/Photo Editor/tempcsdk/platforms/ios/cordova/lib/plugman/pluginHandlers.js:53:48)
>     at Object.process (/Volumes/DATA/work/Photo Editor/tempcsdk/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
>     at Plugman.addPlugin (/Volumes/DATA/work/Photo Editor/tempcsdk/platforms/ios/cordova/lib/plugman/Plugman.js:81:20)
>     at Api.addPlugin (/Volumes/DATA/work/Photo Editor/tempcsdk/platforms/ios/cordova/Api.js:202:40)
>     at handleInstall (/usr/local/lib/node_modules/phonegap/node_modules/cordova-lib/src/plugman/install.js:611:6)
>     at /usr/local/lib/node_modules/phonegap/node_modules/cordova-lib/src/plugman/install.js:407:28
>     at _fulfilled (/usr/local/lib/node_modules/phonegap/node_modules/q/q.js:787:54)
>     at self.promiseDispatch.done (/usr/local/lib/node_modules/phonegap/node_modules/q/q.js:816:30)
>     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/phonegap/node_modules/q/q.js:749:13)
>     at /usr/local/lib/node_modules/phonegap/node_modules/q/q.js:509:49
> 
> 
> Error: Uh oh!
> cannot find "/Volumes/DATA/work/Photo Editor/tempcsdk/plugins/phonegap-plugin-csdk-client-auth/src/ios/AdobeCreativeSDKFrameworks/AdobeCreativeSDKCore.framework/Versions/A/Resources/AdobeCreativeSDKCoreResources.bundle" ios <resource-file>

**Comment by macdonst** [comment]
@hvadotnarola did you follow step 4 of the setup guide? 

https://github.com/CreativeSDK/phonegap-template-csdk-image-editor#setup-guide

**Comment by ghost** [comment]
Yes downloaded frameworks zip and extracted all files (.framework) to plugin's src/ios folders.

**Comment by macdonst** [comment]
@hvadotnarola remove the ios platform and try again.

```
phonegap platform rm ios
phonegap platform add ios
```

**Comment by ghost** [comment]
Yes adding platform is giving above error.

**Comment by macdonst** [comment]
@hvadotnarola you used the `STATIC FRAMEWORKS (DEPRECATED) ` link right?

**Comment by ghost** [comment]
Yes below demo projects.
